name: Build and push a development version on docker 

on: 
  workflow_dispatch: 
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10+7'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build -x test

  docker-build:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Create more disk space
        run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: Dockerfile.local
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: lfoppiano/grobid-quantities
          registry: docker.io
          pushImage: true
          tags: latest-develop
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}