name: Run integration tests manually

on:
   - workflow_dispatch
   - push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout grobid home
      uses: actions/checkout@v4
      with:
        repository: kermitt2/grobid
        path: grobid-home
        sparse-checkout: |
          grobid-home/
        sparse-checkout-cone-mode: false
    - name: Checkout grobid-quantities
      uses: actions/checkout@v4
      with:
        repository: kermitt2/grobid
        path: grobid-quantities
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10+7'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      working-directory: ./grobid-quantities
      run: ./gradlew build -x test
    - name: Run integration tests
      working-directory: ./grobid-quantities
      run: ./gradlew integration

#    - name: Coveralls GitHub Action
#      uses: coverallsapp/github-action@v2
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        format: jacoco
